server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@cluster0.sblzgnn.mongodb.net/chessdb?retryWrites=true&w=majority&appName=Cluster0
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: chess-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  chess:
    kafka:
      topic: chess-moves
